"""Synthetic Standard Notes diary backup for testing SNChat end-to-end.

Generated by Claude Fable 5. Any resemblance to real persons, living or dead,
is purely coincidental.

A deterministic Czech mock diary (2025-01 .. 2026-06) whose content encodes the
regression scenarios from docs/error_modes.md §6, plus ground-truth constants that
tests assert against (see docs/mock_diary.md for the full answer key). `build_zip()`
emits the exact ZIP layout `parser.parse_standard_notes()` expects, including
edge-case notes that MUST be skipped (no date prefix, invalid date, deleted item,
non-note item, empty text).

Build a ZIP to ingest manually in the app sidebar:

    uv run python tests/mock_diary.py [mock_diary.zip]

Deliberately stdlib-only (no app/langchain imports) so the CLI stays instant.
"""

from dataclasses import dataclass
import datetime as dt
import json
from pathlib import Path
import uuid
import zipfile

SN_VERSION = "004"


@dataclass(frozen=True)
class Entry:
    date: str  # ISO yyyy-mm-dd; becomes the note-title prefix (the data contract)
    title: str
    text: str
    tags: tuple[str, ...] = ()


# --- Skiing: distinct 2025 vs 2026 story lines so the follow-up scope test
# ("how was skiing in 2025?" -> "and in 2026?") has human-checkable answers.
# 2025 = old worn-out skis, broken pole; 2026 = new Atomic skis, avalanche course.
SKIING = [
    Entry(
        "2025-01-04",
        "Lyže Špindl",
        "První lyžovačka sezóny ve Špindlerově Mlýně. Sjezdovky byly ráno ledové "
        "a odpoledne rozbředlé, na Hromovce jsem upadl a zlomil si hůlku, takže "
        "jsem si musel půjčit novou v půjčovně. I tak to byl super den, večer "
        "jsme si dali klobásu u vleku a nohy bolely ještě v autě.",
        ("lyže",),
    ),
    Entry(
        "2025-01-11",
        "Skialp Sněžka",
        "Vyrazili jsme s Honzou na skialpy do Krkonoš. Nalepili jsme skiny u Pece "
        "a šlapali směrem na Sněžku, ale nahoře foukal tak silný vítr, že jsme to "
        "otočili kousek pod vrcholem. Sjezd v hlubokém sněhu byl ale odměna, "
        "stálo to za to.",
        ("skialp",),
    ),
    Entry(
        "2025-01-19",
        "Lyže s rodinou",
        "Rodinná lyžovačka v Herlíkovicích. Jezdili jsme hlavně modré, ať si to "
        "užije i ségra, odpoledne svařák na terase. Moje staré lyže už mají hrany "
        "úplně pryč, příští sezónu budu muset řešit nové.",
        ("lyže",),
    ),
    Entry(
        "2025-02-08",
        "Skialp Chopok",
        "Víkend v Nízkých Tatrách. Vyšlapali jsme na Chopok, nahoře čerstvý "
        "prašan po celotýdenním sněžení. Sjezd severní stranou byl nejlepší "
        "letošní zážitek na lyžích, sníh po kolena.",
        ("skialp",),
    ),
    Entry(
        "2025-03-01",
        "Jarní firn",
        "Asi poslední lyžovačka sezóny 2025. Jarní firn, teplo, jezdil jsem jen "
        "v mikině. Staré lyže definitivně dosloužily, skelet je prasklý u vázání. "
        "Rozloučil jsem se se sezónou kofolou na sjezdovce.",
        ("lyže",),
    ),
    Entry(
        "2026-01-03",
        "Nové lyže",
        "První den na nových lyžích Atomic, které jsem si koupil o Vánocích! "
        "Vyrazil jsem na Červenohorské sedlo v Jeseníkách. Rozdíl oproti starým "
        "je obrovský, drží v oblouku i na ledu. Nejlepší investice poslední doby.",
        ("lyže",),
    ),
    Entry(
        "2026-01-17",
        "Skialp Praděd",
        "Skialpová hřebenovka v Jeseníkách, od Ovčárny přes Praděd. Bylo minus "
        "patnáct a na hřebeni ledový vítr, ale inverze pod námi vypadala "
        "neskutečně. Nové lyže fungují skvěle i se skiny.",
        ("skialp",),
    ),
    Entry(
        "2026-01-24",
        "Lyže s Petrem",
        "Vytáhl jsem Petra na lyže do Koutů. Ráno perfektní manšestr, trénovali "
        "jsme carvingové oblouky, odpoledne se to rozbilo. Petr je rychlejší než "
        "loni, budu muset přidat.",
        ("lyže",),
    ),
    Entry(
        "2026-02-07",
        "Lavinový kurz",
        "Absolvoval jsem lavinový kurz v Roháčích. Učili jsme se hledat pípákem, "
        "sondovat a kopat sněhový profil. Dost mi to otevřelo oči, doteď jsme na "
        "skialpech dost riskovali.",
        ("skialp",),
    ),
    Entry(
        "2026-02-21",
        "Stubai",
        "Prodloužený víkend na ledovci Stubai v Rakousku. Perfektně upravené "
        "sjezdovky, jen fronty u lanovek byly šílené. Dal jsem si i pár skoků ve "
        "snowparku a kupodivu přežil bez pádu.",
        ("lyže",),
    ),
    Entry(
        "2026-03-08",
        "Poslední skialp",
        "Jarní přechod hřebene na skialpech, sníh už jen místy, chvílemi jsme "
        "lyže nesli na batohu. Krásná tečka za sezónou 2026, letos to bylo díky "
        "novým lyžím a lavinovému kurzu o level jinde.",
        ("skialp",),
    ),
]

# --- Climbing: 12 dated sessions with a clean 5b -> 6b grade progression, so both
# "last 10 climbing sessions" (recent-N) and "how is my climbing going?"
# (progression summary) have checkable ground truth.
CLIMBING = [
    Entry(
        "2025-02-12",
        "Poprvé na stěně",
        "Klára mě konečně dotáhla na lezeckou stěnu. Lezl jsem poprvé v životě "
        "s lanem, zvládl jsem pár cest za 4+ a jednu 5b na top rope. Předloktí "
        "mám úplně mrtvá, ale hrozně mě to chytlo.",
        ("lezení",),
    ),
    Entry(
        "2025-03-05",
        "Druhá lekce lezení",
        "Podruhé na stěně. 5c mi už šla celkem plynule, zkusil jsem první 6a, "
        "ale spadl jsem v převisu — síla v prstech zatím není. Klára říká, že "
        "mám lézt nohama, ne rukama.",
        ("lezení",),
    ),
    Entry(
        "2025-04-02",
        "První 6a",
        "Vylezl jsem svou první 6a! Klíčové místo v převisu jsem tentokrát "
        "přelezl na první pokus. Postupně chápu, co znamená lézt technicky. "
        "Odměna: velká pizza.",
        ("lezení",),
    ),
    Entry(
        "2025-05-14",
        "Moravský kras",
        "Poprvé lezení venku, na vápenci v Moravském krasu. Na skále je všechno "
        "jinak než na stěně — chyty se musí hledat a 5c venku byla těžší než 6a "
        "uvnitř. Nádherný den, prsty rozedřené.",
        ("lezení",),
    ),
    Entry(
        "2025-06-20",
        "Via ferrata Vír",
        "Via ferrata u Víru, obtížnost C. Expozice nad přehradou byla parádní, "
        "chvílemi se mi klepaly nohy. Dobrý trénink hlavy na lezení.",
        ("lezení",),
    ),
    Entry(
        "2025-08-09",
        "Boulder session",
        "Bouldering s Klárou. Přeskočil jsem na 6a flash, dokonce jsem dal jeden "
        "boulder za 6a+ po pár pokusech. Síla se pomalu dostavuje, visy na liště "
        "začínají fungovat.",
        ("lezení",),
    ),
    Entry(
        "2025-09-17",
        "Sloup",
        "Lezení venku na Sloupu. Dal jsem svou první venkovní 6a na druhý pokus. "
        "Konečně se venkovní lezení srovnává s tím na stěně.",
        ("lezení",),
    ),
    Entry(
        "2025-11-06",
        "Stěna po pauze",
        "Po měsíční pauze zpátky na stěně. Šlo to hůř, než jsem čekal, na 6a "
        "jsem dvakrát odpadl. Domluvili jsme si s Klárou pravidelné středy, ať "
        "se to zase rozjede.",
        ("lezení",),
    ),
    Entry(
        "2026-01-28",
        "Zimní trénink",
        "Zimní lezecký trénink: visy na liště, přítahy a technika na kolmé "
        "stěně. 6a+ už dávám celkem jistě. Cíl na jaro je jasný: 6b.",
        ("lezení",),
    ),
    Entry(
        "2026-03-15",
        "První 6b",
        "Dal jsem první 6b na stěně! Zkoušel jsem ji čtyři středy po sobě a dnes "
        "to konečně klaplo. Progres od února 2025 je neuvěřitelný, z 5b na 6b za "
        "rok.",
        ("lezení",),
    ),
    Entry(
        "2026-04-25",
        "Adršpach",
        "Výlet na písek do Adršpachu. Lezení na pískovci je úplně jiný sport, "
        "spáry bolí a jištění je pro odvážné. Lezl jsem jen lehké cesty jako "
        "druhý na laně, ale zážitek obrovský.",
        ("lezení",),
    ),
    Entry(
        "2026-06-10",
        "První 6b venku",
        "Vylezl jsem první venkovní 6b, na prvním konci lana! Sezóna 2026 je "
        "zatím lezecky nejlepší, co jsem kdy měl. Klára navrhuje na podzim "
        "lezecký výjezd do Arca.",
        ("lezení",),
    ),
]

# --- Running: distances are stated so "kolik jsem toho naběhal?" is checkable
# (5 + 10 + 21.1 + 8 + 12 = 56.1 km); the newest entry answers "my last run".
RUNNING = [
    Entry(
        "2025-04-10",
        "První jarní běh",
        "První letošní běh venku. Dal jsem 5 km za 31 minut, kondice přes zimu "
        "dost spadla. Plán je běhat dvakrát týdně a na podzim zkusit půlmaraton.",
        ("běh",),
    ),
    Entry(
        "2025-06-15",
        "Desítka s osobákem",
        "Uběhl jsem 10 km za 52:30, nový osobák! Trasa kolem řeky, ráno, "
        "příjemných osmnáct stupňů. Tréninkový plán funguje, příště zkusím delší "
        "tempo.",
        ("běh",),
    ),
    Entry(
        "2025-09-21",
        "Půlmaraton Ústí",
        "Doběhl jsem půlmaraton v Ústí nad Labem! 21,1 km za 2:05:47. Posledních "
        "pět kilometrů bylo utrpení, ale medaile visí. Splněný cíl sezóny, teď "
        "chvíli odpočinek.",
        ("běh",),
    ),
    Entry(
        "2026-02-14",
        "Běh na pásu",
        "Venku ledovka, tak aspoň 8 km na pásu ve fitku. Nuda, ale aspoň něco. "
        "Těším se na jaro, běhání venku je nesrovnatelné.",
        ("běh",),
    ),
    Entry(
        "2026-05-30",
        "Nové boty",
        "První běh v nových botách, 12 km a nohy jak v peřině. Měl jsem je "
        "koupit dávno, staré měly naběháno přes tisíc kilometrů. Tempo 5:40 na "
        "kilometr a cítil jsem se skvěle.",
        ("běh",),
    ),
]

# --- Thesis/exams arc; the anxiety wording ("úzkost", "nervózní") is the ground
# truth for the thematic negative control ("when did I feel anxious?" must route
# semantically, NOT through the keyword branch). Kept OUT of the filler pools.
STUDIES = [
    Entry(
        "2025-03-20",
        "Osnova diplomky",
        "Sešel jsem se s vedoucím a odsouhlasili jsme osnovu diplomky. Téma je "
        "zajímavé, ale rozsah mě trochu děsí. Založil jsem repozitář a začal "
        "rešerši literatury.",
        ("diplomka",),
    ),
    Entry(
        "2025-04-28",
        "Experimenty selhávají",
        "Celý den ladím experimenty k diplomce a výsledky pořád nedávají smysl. "
        "Cítil jsem docela úzkost z toho, že to nestihnu dopsat včas. Vedoucí mě "
        "uklidňoval, že datová část se vždycky nějak srovná, ale moc to "
        "nepomohlo.",
        ("diplomka",),
    ),
    Entry(
        "2025-05-25",
        "Učení na státnice",
        "Učím se na státnice, okruhy z algoritmů a databází. Byl jsem celý den "
        "hodně nervózní a v noci jsem špatně spal, pořád se mi honí hlavou, co "
        "všechno ještě neumím. Klára mi vyrobila kartičky na opakování.",
        ("státnice",),
    ),
    Entry(
        "2025-06-09",
        "Složeno",
        "Státnice jsou za mnou! Obhajoba diplomky proběhla překvapivě v klidu, "
        "komise se ptala přesně na to, co jsem čekal. Obrovská úleva, večer "
        "oslava s celým ročníkem. Zítra nedělám vůbec nic.",
        ("státnice", "diplomka"),
    ),
]

# --- Trips: the Pálava entry is the exact-date point lookup from error_modes §6.4
# ("what did I do on 2025-05-18?"); Kutná Hora plants "gotická/gotických" as the
# whole-word negative control for the "GoT" acronym match.
TRIPS = [
    Entry(
        "2025-05-18",
        "Pálava",
        "Celodenní výlet na Pálavu. Vyšlapali jsme přes Děvín na Dívčí hrady, "
        "kvetly kosatce a výhled na Novomlýnské nádrže byl parádní. Cestou "
        "zpátky ochutnávka vína v Pavlově, domů jsme dojeli až za tmy.",
        ("turistika",),
    ),
    Entry(
        "2025-09-03",
        "Kutná Hora",
        "Výlet do Kutné Hory. Gotická katedrála svaté Barbory je ohromující, "
        "klenba vypadá jako krajka. Prošli jsme i historické centrum plné "
        "gotických domů a kostnici v Sedlci. Doporučil bych každému.",
        ("turistika",),
    ),
]

# --- Named entity #1: Game of Thrones. 12 mentions (more than SEARCH_K=10)
# scattered across untagged entries, rotating the surface forms the extraction LLM
# expands to: EN name, "GoT" acronym, Czech base form and DECLINED Czech forms.
# The 2025-07-15 entry is deliberately LONG with the mention buried mid-paragraph
# (the WRatio length-ratio regression, error_modes §2.6).
GOT_ENTRIES = [
    Entry(
        "2025-01-07",
        "Nový seriál",
        "Začal jsem konečně sledovat Game of Thrones, kamarádi mě k tomu "
        "přemlouvali roky. První dva díly mě úplně pohltily, hlavně prostředí "
        "Zimohradu. Uvidíme, jestli to vydrží.",
    ),
    Entry(
        "2025-01-21",
        "Večer u seriálu",
        "Další epizody GoT, konečně se to pořádně rozjelo. Koukali jsme s Klárou "
        "do půlnoci, což ráno nebyl dobrý nápad. Ned Stark je můj favorit.",
    ),
    Entry(
        "2025-02-03",
        "Debata s kamarády",
        "Na pivu jsme se celý večer bavili o seriálu Hra o trůny. Tomáš mi "
        "vyspoiloval jednu svatbu, naštěstí jen napůl. Musím zrychlit tempo "
        "sledování.",
    ),
    Entry(
        "2025-02-18",
        "Postavy",
        "Přemýšlel jsem, proč mě ve Hře o trůny nejvíc baví záporáci. Cersei je "
        "skvěle napsaná postava, i když ji nesnáším. Večer dva díly a spát.",
    ),
    Entry(
        "2025-03-11",
        "Rudá svatba",
        "Tak Rudá svatba v GoT mě naprosto rozložila. Seděl jsem pak deset minut "
        "v tichu a zíral do zdi. Tomáš se mi směje, že mě varoval.",
    ),
    Entry(
        "2025-04-06",
        "Seriálový maraton",
        "Deštivá neděle, tak jsme s Klárou dali maraton Game of Thrones, pět "
        "dílů v kuse. Objednali jsme si pizzu a nevylezli z gauče. Dračí scény "
        "jsou i po letech ohromující.",
    ),
    Entry(
        "2025-04-22",
        "Doporučení mámě",
        "Doporučil jsem Hru o trůny mámě, což byla možná chyba — už mi volala "
        "třikrát, že nemůže přestat. Aspoň máme společné téma na nedělní obědy.",
    ),
    Entry(
        "2025-05-09",
        "Odměna za učení",
        "Celý den učení na státnice, večer jsem si jako odměnu pustil jeden díl "
        "GoT. Pomáhá mi to vypnout hlavu. Zbývají poslední dvě série.",
    ),
    Entry(
        "2025-06-02",
        "Slabší série",
        "Poslední série Hry o trůny začíná nějak uspěchaně. Vývoj postav, který "
        "se budoval roky, se láme přes koleno. Doufám, že se to zvedne, ale "
        "nečekám zázraky.",
    ),
    Entry(
        "2025-07-15",
        "Dlouhý den",
        "Ráno mě vzbudil telefonát už v šest třicet, v práci spadla databáze a "
        "nikdo jiný nebyl k zastižení, takže jsem to do devíti řešil z domova v "
        "pyžamu. Nakonec se ukázalo, že za to mohla plná fronta logů, klasika, "
        "kterou jsme měli vyřešit už před půl rokem. Dopoledne pak porada, která "
        "se protáhla na dvě hodiny, ačkoli se probraly asi tři skutečně důležité "
        "věci. Odpoledne jsem si vzal chvíli volno a zajel vyzvednout kolo ze "
        "servisu, vyměnili mi řetěz a přehazovačku, jezdí zase jako nové. Cestou "
        "zpátky jsem nakoupil na víkend a stavil se u rodičů, táta potřeboval "
        "pomoct přenést skříň a máma mě samozřejmě nepustila bez bábovky. Večer "
        "jsem si pustil další díl Game of Thrones a u toho vyžehlil hromadu "
        "prádla, co se válela v ložnici od minulého týdne. Seriál se blíží ke "
        "konci a já pořád nevím, co si o posledních dílech myslet. Před spaním "
        "ještě chvíle čtení a rychlá kontrola kalendáře na zítřek, čeká mě další "
        "dlouhý den.",
    ),
    Entry(
        "2025-08-30",
        "Rewatch",
        "S Tomášem jsme si pustili pár oblíbených scén z GoT, hlavně bitvu "
        "bastardů. Pořád to má atmosféru. Domluvili jsme se, že příští rok "
        "zkusíme knihy.",
    ),
    Entry(
        "2025-10-12",
        "Dokoukáno",
        "Dokoukal jsem Hru o trůny. Konec mě, jako asi všechny, trochu zklamal — "
        "poslední série je uspěchaná a rozhodnutí postav nedávají smysl. Ale "
        "prvních šest sérií patří k tomu nejlepšímu, co jsem kdy viděl. Celkový "
        "dojem: 8 z 10, škoda konce.",
    ),
]

# --- Named entity #2: the Witcher books — a second, smaller entity with Czech
# declensions (Zaklínač/Zaklínače/Zaklínači) plus the English show name.
WITCHER_ENTRIES = [
    Entry(
        "2025-11-20",
        "Poslední přání",
        "Začal jsem číst Zaklínače, první povídkovou knihu Poslední přání. "
        "Geraltův suchý humor mě baví víc, než jsem čekal. Čtu dlouho do noci, "
        "což se mi u knížky nestalo hodně dlouho.",
    ),
    Entry(
        "2025-12-05",
        "Druhý díl",
        "Dočetl jsem druhý díl Zaklínače, Meč osudu. Povídka s Ciri na konci je "
        "nejsilnější věc, co jsem letos četl. Vánoční dárek pro sebe: zbytek "
        "ságy.",
    ),
    Entry(
        "2026-01-15",
        "Seriálové srovnání",
        "Pustil jsem si první díly seriálu The Witcher. Po knihách mě trochu "
        "ruší přeházená chronologie, ale souboje jsou skvělé. Knihy zatím vedou.",
    ),
    Entry(
        "2026-03-22",
        "Debata u piva",
        "U piva jsme se s Tomášem hádali o Zaklínači — on tvrdí, že hry jsou "
        "lepší než knihy. Nemám odehráno, takže jsem argumentačně prohrál. Možná "
        "si trojku o prázdninách zahraju.",
    ),
]

# --- Misc: a cross-year anxiety mention (untagged) and the English "forgot"
# negative control ("got" must not match inside "forgot").
MISC = [
    Entry(
        "2026-01-10",
        "Nervy z nové práce",
        "V pondělí nastupuji do nové práce a celý víkend cítím úzkost. "
        "Racionálně vím, že je to nesmysl, ale stejně jsem nervózní z nového "
        "kolektivu. Pomohla dlouhá procházka a rozhovor s Klárou.",
    ),
    Entry(
        "2026-02-02",
        "Anglický trapas",
        "V práci jsem psal americkému kolegovi a omylem mu poslal nedokončenou "
        "zprávu. Odpověděl jen „no worries, I forgot to reply anyway“ a hned to "
        "bylo lepší. Musím si zase zapnout kontrolu pravopisu.",
    ),
]

_HANDCRAFTED = [
    *SKIING,
    *CLIMBING,
    *RUNNING,
    *STUDIES,
    *TRIPS,
    *GOT_ENTRIES,
    *WITCHER_ENTRIES,
    *MISC,
]

# --- Filler: mundane, untagged entries that (a) push year 2025 past FETCH_ALL_MAX
# entries AND past SINGLE_PASS_BUDGET chars (so breadth=all triggers fetch-all +
# map-reduce), and (b) act as noise the keyword/tag/date filters must NOT match.
# Deterministic sentence rotation — no randomness, no named entities, and none of
# the ground-truth trigger words (got/trůny/zaklínač/witcher/úzkost/nervózní).

_WEATHER = (
    "Celý den poprchávalo a nálada tomu odpovídala, aspoň se dobře sedělo uvnitř.",
    "Krásně slunečno, skoro škoda trávit takový den prací.",
    "Od rána hustá mlha, která se zvedla až kolem oběda.",
    "Foukalo tak, že lidem na ulici létaly deštníky z rukou.",
    "Mrazivé ráno, odpoledne se ale vyčasilo a slunce hřálo i přes okno.",
    "Celý den těžké dusno a večer konečně přišla pořádná bouřka.",
)

_WORK = (
    "Ráno standup a pak jsem celé dopoledne ladil jeden zapeklitý problém v "
    "deploy pipeline, který se nakonec ukázal být překlepem v konfiguraci.",
    "Dopoledne dvě schůzky za sebou, mezi nimi jsem stihl aspoň projít e-maily a "
    "naplánovat si úkoly na zbytek týdne.",
    "V práci klidný den, dopisoval jsem dokumentaci k nové službě a odbavil pár "
    "code review, která na mě čekala od pondělí.",
    "Ráno jsem zaspal a dohnal to až odpoledne, dopoledne bylo hlavně o kávě a "
    "mechanických úkolech, které nevyžadují moc přemýšlení.",
    "Celé dopoledne jsem refaktoroval starý modul, do kterého se roky nikomu "
    "nechtělo. Nevděčná, ale očistná práce.",
    "Dopoledne jsem strávil přípravou prezentace pro tým, odpoledne jsem ji "
    "odprezentoval a kupodivu nepřišly skoro žádné dotazy.",
    "Pracovní den plný drobností: aktualizace závislostí, dvě rychlé opravy a "
    "dlouhá diskuze o pojmenování jedné funkce.",
    "Ráno mi ujel autobus, tak jsem šel pěšky a do práce dorazil s "
    "dvacetiminutovým zpožděním, ale aspoň provětraný.",
)

_AFTERNOON = (
    "Odpoledne jsem zajel na velký nákup a konečně doplnil zásoby, lednice byla "
    "poslední dny zoufale prázdná.",
    "Po obědě jsem si dal krátkého šlofíka a pak vyřídil hromadu restů: pošta, "
    "lékárna a vyzvednutí balíku.",
    "Odpoledne úklid bytu, vysál jsem, vytřel a vynesl tři pytle věcí, které se "
    "tu jen tak válely.",
    "Odpoledne jsem pomáhal sousedovi stěhovat pohovku do třetího patra, záda mi "
    "to připomínala až do večera.",
    "Po práci jsem se zastavil v knihovně vrátit knížky a samozřejmě odešel se "
    "třemi novými.",
    "Odpoledne jsem strávil na zahradě u rodičů, stříhali jsme keře a pálili "
    "větve, voněl celý dvůr.",
    "Odpoledne jsem opravoval kapající kohoutek v koupelně, dvě cesty do "
    "železářství, ale nakonec úspěch.",
)

_DINNER = (
    "K večeři jsem uvařil velký hrnec guláše, ať mám na pár dní dopředu, a "
    "povedl se výjimečně.",
    "Večer jsem zkusil nový recept na rizoto s houbami, trochu jsem to přesolil, "
    "ale jinak dobré.",
    "Uvařil jsem čočku na kyselo podle babiččina receptu, s cibulkou a vejcem, "
    "klasika, která nezklame.",
    "Na večeři těstoviny s pestem a spousta parmazánu, rychlovka, když se "
    "nechce vařit.",
    "Upekl jsem kuře na paprice, omáčka se povedla krémová, knedlíky ale "
    "kupované, na vlastní nebyl čas.",
    "Večeře byla jen studená kuchyně, chleba se sýrem a zelenina, po velkém "
    "obědě nebyl hlad.",
    "Zkusil jsem poprvé smaženici z hub, které jsme našli o víkendu, a byla "
    "vynikající.",
    "K večeři bramboračka z pytlíku vylepšená klobásou, kulinářsky dno, ale zahřála.",
)

_EVENING = (
    "Večer jsem četl detektivku, mám rozečtenou už třetí od stejné autorky a "
    "pořád mě baví.",
    "Večer jsme si zavolali s rodiči, probrali jsme plány na léto a mámin nový záhon.",
    "Po večeři procházka kolem řeky, potkal jsem souseda se psem a probrali jsme "
    "počasí i politiku.",
    "Večer dokument o oceánech, u kterého jsem napůl usnul, ale záběry velryb "
    "stály za to.",
    "Se sousedy jsme večer hráli deskovky, prohrál jsem všechny tři partie, ale "
    "se ctí.",
    "Večer jsem třídil fotky z telefonu, dva tisíce snímků a z toho polovina "
    "rozmazaná.",
    "Večer jsem si pustil hudbu a hodinu jen tak přebíral věci na stole, "
    "meditativní činnost.",
)

_REFLECTION = (
    "Přemýšlel jsem u toho, jak rychle ten rok utíká — ještě nedávno jsem psal "
    "novoroční plány a najednou je další kus roku pryč. Ta důležitá "
    "předsevzetí, víc se hýbat a míň sedět u telefonu, se ale zatím drží.",
    "Uvědomil jsem si, že mi tenhle obyčejný rytmus vlastně vyhovuje: práce, "
    "jídlo, chvíle pro sebe. Ne každý den musí být výjimečný, aby stál za "
    "zapsání do deníku.",
    "Večer jsem chvíli listoval staršími zápisky v deníku a bavilo mě, kolik "
    "drobností bych si jinak vůbec nepamatoval. Psaní se vyplácí, i když se mi "
    "občas nechce.",
    "Říkal jsem si, že bych měl častěji vytáhnout foťák a míň fotit telefonem, "
    "staré fotky z brigády vypadají líp než cokoli z posledního roku. Možná "
    "projekt na příští měsíc.",
    "Napadlo mě, že bych mohl zase někam vyrazit na delší výlet, dlouho jsem "
    "nikde nebyl. Zatím z toho je jen otevřená mapa na stole a čárky u míst, "
    "která zní dobře.",
)

_CLOSING = (
    "Spát jsem šel dřív než obvykle a těšil se na to celý den.",
    "Usínal jsem u otevřeného okna, venku bylo slyšet jen vítr.",
    "Před spaním ještě rychlá kontrola kalendáře, zítra běžný den.",
    "Den bez velkých událostí, ale přesně takové mám vlastně nejradši.",
    "Byl to dlouhý den, ale spokojenost, většinu plánu jsem stihl.",
    "Únava veliká, ale příjemná, zítra snad klidnější program.",
)

_WEEKDAYS = ("Pondělí", "Úterý", "Středa", "Čtvrtek", "Pátek", "Sobota", "Neděle")


def _filler_text(i: int) -> str:
    """Deterministic mundane-day text; co-prime pool sizes keep combos varied."""
    return " ".join(
        (
            _WEATHER[i % len(_WEATHER)],
            _WORK[i % len(_WORK)],
            _AFTERNOON[(i + 2) % len(_AFTERNOON)],
            _DINNER[(i * 3 + 1) % len(_DINNER)],
            _EVENING[(i + 4) % len(_EVENING)],
            _REFLECTION[i % len(_REFLECTION)],
            _CLOSING[(i * 2) % len(_CLOSING)],
        )
    )


def _filler_entries() -> list[Entry]:
    reserved = {e.date for e in _HANDCRAFTED}
    out: list[Entry] = []
    i = 0
    for start, end, step in (
        (dt.date(2025, 1, 2), dt.date(2025, 12, 31), 6),
        (dt.date(2026, 1, 5), dt.date(2026, 6, 30), 10),
    ):
        day = start
        while day <= end:
            iso = day.isoformat()
            if iso not in reserved:
                out.append(Entry(iso, _WEEKDAYS[day.weekday()], _filler_text(i)))
                i += 1
            day += dt.timedelta(days=step)
    return out


ENTRIES: list[Entry] = sorted(_HANDCRAFTED + _filler_entries(), key=lambda e: e.date)

# --- Ground truth (see docs/mock_diary.md for the prompt-level answer key) ---
TAGS = ("běh", "diplomka", "lezení", "lyže", "skialp", "státnice", "turistika")

# Surface forms the extraction LLM is expected to expand each entity into.
GOT_KEYWORDS = ("GoT", "Game of Thrones", "Hra o trůny")
GOT_DATES = tuple(e.date for e in GOT_ENTRIES)
WITCHER_KEYWORDS = ("Zaklínač", "The Witcher")
WITCHER_DATES = tuple(e.date for e in WITCHER_ENTRIES)
# Entries that LOOK like keyword hits but must not match ("gotická", "forgot").
KEYWORD_NEGATIVE_DATES = ("2025-09-03", "2026-02-02")

CLIMBING_DATES = tuple(e.date for e in CLIMBING)  # chronological
RUNNING_DATES = tuple(e.date for e in RUNNING)
LAST_RUN_DATE = RUNNING_DATES[-1]
JANUARY_SKIING_DATES = tuple(e.date for e in SKIING if e.date[5:7] == "01")
ANXIETY_DATES = ("2025-04-28", "2025-05-25", "2026-01-10")  # semantic-only GT
POINT_LOOKUP_DATE = "2025-05-18"  # the Pálava trip

# Parsed by the parser (valid date title) but skipped at indexing (empty text).
EMPTY_TEXT_DATE = "2026-06-28"


def _uuid(name: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"snchat-mock:{name}"))


# Items the parser / ingestion must SKIP (error_modes §5 + ingestion filters).
EDGE_ITEMS: list[dict] = [
    {
        # No ISO-date title prefix -> silently skipped (data contract).
        "uuid": _uuid("edge:no-date"),
        "content_type": "Note",
        "content": {"title": "Nápady na dárky", "text": "Ponožky, kniha, čelovka."},
    },
    {
        # Invalid calendar date -> date.fromisoformat raises -> skipped.
        "uuid": _uuid("edge:bad-date"),
        "content_type": "Note",
        "content": {"title": "2025-02-30 Chyba", "text": "Tohle datum neexistuje."},
    },
    {
        # Deleted note -> skipped.
        "uuid": _uuid("edge:deleted"),
        "content_type": "Note",
        "deleted": True,
        "content": {"title": "2025-08-15 Smazáno", "text": "Tohle bylo smazáno."},
    },
    {
        # Non-note item in the main backup file -> skipped by content_type.
        "uuid": _uuid("edge:non-note"),
        "content_type": "Tag",
        "content": {"title": "osobní"},
    },
    {
        # Valid date but EMPTY text -> parsed, then skipped at indexing.
        "uuid": _uuid("edge:empty-text"),
        "content_type": "Note",
        "content": {"title": f"{EMPTY_TEXT_DATE} Prázdný den", "text": ""},
    },
]


def build_zip(path: Path) -> Path:
    """Write the mock diary as a Standard Notes backup ZIP at `path`."""
    items: list[dict] = []
    tag_refs: dict[str, list[str]] = {}
    for e in ENTRIES:
        note_uuid = _uuid(f"{e.date}:{e.title}")
        items.append(
            {
                "uuid": note_uuid,
                "content_type": "Note",
                "created_at": f"{e.date}T20:30:00.000Z",
                "updated_at": f"{e.date}T21:00:00.000Z",
                "content": {
                    "title": f"{e.date} {e.title}",
                    "text": e.text,
                    "references": [],
                },
            }
        )
        for tag in e.tags:
            tag_refs.setdefault(tag, []).append(note_uuid)
    items.extend(EDGE_ITEMS)

    backup = {"version": SN_VERSION, "items": items}
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(
            "Standard Notes Backup and Import File.txt",
            json.dumps(backup, ensure_ascii=False, indent=2),
        )
        for tag, refs in sorted(tag_refs.items()):
            tag_file = {
                "uuid": _uuid(f"tag:{tag}"),
                "content_type": "Tag",
                "title": tag,
                "references": [{"uuid": u, "content_type": "Note"} for u in refs],
            }
            zf.writestr(
                f"Items/Tag/{tag}.txt",
                json.dumps(tag_file, ensure_ascii=False, indent=2),
            )
    return path


if __name__ == "__main__":
    import sys

    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("mock_diary.zip")
    build_zip(out)
    print(
        f"Wrote {out} — {len(ENTRIES)} diary entries "
        f"({sum(bool(e.tags) for e in ENTRIES)} tagged) "
        f"+ {len(EDGE_ITEMS)} edge-case notes."
    )
